name: Docker Image CI
"on":
  push:
    branches: [main]
jobs:
  # test:
  #   name: Run test suite
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Make tests
  #       run: make tests
  publish:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build
        run: nix build .#docker
      - name: Load
        run: docker load < result
      - name: Publish
        run: docker push $DOCKER_USER/mv-mcp
